# An example of a fully described value file for describing the simplest rbac
---
# Description of the rbac
# ServiceAccount, Role, RoleBinding
rbac:
  - name: serviceaccount-example
    rules:
      # The name of the api to which access is required for the service account
      - apiGroups:
          - ""
        # List of resources that ServiceAccount will have access to
        resources:
          - pods
        # List of rights to resources that ServiceAccount will have
        verbs:
          - get
          - watch
          - list
