---
# Default values for wireguard-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# This chart deploys the WireGuard Operator to your Kubernetes cluster from this repository: https://github.com/jodevsa/wireguard-operator

# Settings for the kube-rbac-proxy sidecar container
proxy:
  image:
    repository: ghcr.io/obervinov/images/kube-rbac-proxy
    tag: v0.8.0
  resources:
    limits:
      cpu: 0
      memory: 128Mi
    requests:
      cpu: 0
      memory: 64Mi

# Settings for the injected agent sidecar container
agent:
  image:
    repository: ghcr.io/jodevsa/wireguard-operator/agent
    tag: v2.7.0

# Settings for the main manager container
replicas: 1
image:
  repository: ghcr.io/jodevsa/wireguard-operator/manager
  tag: v2.7.0
resources:
  limits:
    cpu: 0
    memory: 128Mi
  requests:
    cpu: 0
    memory: 64Mi
