{{- if or $.Values.registrationTokens $.Values.runnerTokens }}
{{-   range .Values.runners }}
{{-     $name := .name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitlab-runner.fullname" (list $ . $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "gitlab-runner.fullname" (list $ . $name) }}
    chart: {{ include "gitlab-runner.chart" $ }}
type: Opaque
data:
{{-     if $.Values.registrationTokens }}
{{-       $registrationTokens := fromYaml $.Values.registrationTokens }}
  runner-registration-token: {{ get $registrationTokens $name |  b64enc | quote }}
{{-     else }}
  runner-registration-token: ""
{{-     end -}}
{{-     if $.Values.runnerTokens }}
{{-       $runnerTokens := fromYaml $.Values.runnerTokens }}
  runner-token: {{ get $runnerTokens $name |  b64enc | quote }}
{{-     else }}
  runner-token: ""
{{-     end }}
...

{{-   end -}}
{{- end -}}