{{- if $.Values.global.rbac.create -}}
{{-   range .Values.runners }}
{{-   $name := .name}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{- range $key, $value := $.Values.global.rbac.serviceAccountAnnotations }}
    {{   $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ include "gitlab-runner.fullname" (list $ . $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "gitlab-runner.fullname" (list $ . $name) }}
    chart: {{ include "gitlab-runner.chart" $ }}
{{- if $.Values.global.rbac.imagePullSecrets }}
imagePullSecrets:
  {{- range $.Values.global.rbac.imagePullSecrets }}
  - name: {{ . | quote }}
  {{- end }}
{{- end }}

...
{{-   end -}}
{{- end -}}