{{- if .Values.wireguard       }}
{{-   range .Values.wireguards }}
{{-     $instance := .         }}
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: {{ include "wireguard-operator-crds.fullname" . }}-{{ $instance.name }}
    labels:
      {{- include "wireguard-operator-crds.labels" . | nindent 4 }}
spec:
  mtu: {{ default "1380" $instance.mtu }}
  {{- if $instance.nodePort }}
  serviceType: "NodePort"
  {{- end }}
...
{{-   end }}
{{- end   }}