{{- if .Values.wireguards      }}
{{-   range .Values.wireguards }}
{{-     $instance := .         }}
---
apiVersion: vpn.wireguard-operator.io/v1alpha1
kind: Wireguard
metadata:
  name: {{ include "wireguard-operator-crds.name" $ }}-{{ $instance.name }}
  labels: {{- include "wireguard-operator-crds.labels" $ | nindent 6 }}
spec:
  mtu: {{ default "1380" $instance.mtu }}
  {{- if $instance.serviceAnnotations }}
  serviceAnnotations: {{ toYaml $instance.serviceAnnotations | nindent 4 }}
  {{- end }}
  {{- if $instance.nodePort }}
  serviceType: "NodePort"
  port: {{ $instance.nodePort }}
  {{- end }}
  {{- if $instance.address }}
  address: {{ $instance.address }}
  {{- end }}
  {{- if $instance.agent }}
  agent: {{ toYaml $instance.agent | nindent 4 }}
  {{- end }}
  {{- if $instance.dns }}
  dns: {{ $instance.dns }}
  {{- end }}
  {{- if $instance.metric }}
  metric: {{ toYaml $instance.metric | nindent 4 }}
  {{- end }}
  {{- if $instance.nodeSelector }}
  nodeSelector: {{ toYaml $instance.nodeSelector | nindent 4 }}
  {{- end }}
...
{{-   end }}
{{- end   }}