global:
  apiName: monitoring.coreos.com
  apiVersion: v1

# sm istio for example 
serviceMonitors:
  - name: istiod
    endpoints:
      - port: http-metrics
        # bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # honorLabels: true
        # path: /metrics
        interval: 30s
        scheme: http
    jobLabel: k8s-app
    namespaceSelectors:
      - istio-system
    labelSelectors:
      app: istiod

podMonitors:
  - name: istio-proxy
    ports:
      - http-envoy-prom
    jobLabel: k8s-app
    labelSelectors:
      istio-proxy: "true"
    namespaceSelector:
      any: true
      # matchNames:
      #  - namespace1
      #  - namespace2
