{{-   $fullName := include "collector.fullname" . }}
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ $fullName }}-grpc-vs
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  displayName: {{ $fullName }}-grpc-vs
  virtualHost:
    domains:
      - {{ $fullName }}-grpc.{{.Values.virtualservices.domainPrefix}}*
    routes:
    - options:
        {{- if .Values.virtualservices.timeout }}
        timeout: {{ .Values.virtualservices.timeout }}
        {{- end }}
      routeAction:
        single:
          upstream:
            name: {{ $.Release.Namespace }}-{{ $fullName }}-svc-{{ .Values.virtualservices.grpc }}
            namespace: gloo-system
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: {{ $fullName }}-otlp-vs
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
spec:
  displayName: {{ $fullName }}-otlp-grpc-vs
  virtualHost:
    domains:
      - {{ $fullName }}-otlp.{{.Values.virtualservices.domainPrefix}}*
    routes:
    - options:
        {{- if .Values.virtualservices.timeout }}
        timeout: {{ .Values.virtualservices.timeout }}
        {{- end }}
      routeAction:
        single:
          upstream:
            name: {{ $.Release.Namespace }}-{{ $fullName }}-svc-{{ .Values.virtualservices.otlpgrpc }}
            namespace: gloo-system
...
