{{- if .Values.applications -}}
{{-   range .Values.applications -}}
{{-     if and (.ingress) (.service) -}}
{{-       $name := .name }}
{{-       $fullName := include "universal-template.fullName" (list $ . $name) }}
{{-       $indexLength := (len .ingress) -}}
 
{{-         range .ingress }}
apiVersion: {{ default "networking.k8s.io/v1" .apiVersion }}
kind: {{ default "Ingress" .kind }}
metadata:
  name: {{ $fullName }}-{{ .name }}-ingress
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
  annotations:
  {{- if .ingressAnnotations}}
    {{ .ingressAnnotations }}
  {{- end }}
spec:
  {{- if .tls }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ .tlsSecretName }}
  {{- end }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - path: {{ default "/" .path }}
        pathType: {{ default "Prefix" .pathType }}
        backend:
          service:
            name: {{ $fullName }}-svc
            port:
              number: {{ default 80 .servicePort }}
  ingressClassName: {{ default "nginx" .ingressClassName }}
...
{{-       end -}}
{{-     end -}}
{{-   end }}
{{- end }}
