{{- if $.Values.global.rbac.create -}}
{{-   range .Values.runners }}
{{-   $name := .name}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if $.Values.global.rbac.clusterWideAccess }}"ClusterRoleBinding"{{ else }}"RoleBinding"{{ end }}
metadata:
  name: {{ include "gitlab-runner.fullname" (list $ . $name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ include "gitlab-runner.fullname" (list $ . $name) }}
    chart: {{ include "gitlab-runner.chart" $ }}
  {{ if not $.Values.global.rbac.clusterWideAccess -}}
  namespace: "{{ .Release.Namespace }}"
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if $.Values.global.rbac.clusterWideAccess }}"ClusterRole"{{ else }}"Role"{{ end }}
  name: {{ include "gitlab-runner.fullname" (list $ . $name) }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitlab-runner.fullname" (list $ . $name) }}
  namespace: {{ $.Release.Namespace }}
...

{{-   end -}}
{{- end -}}