---
apiVersion: v2
name: jaeger-stack
version: 1.0.0
description: Helm-chart with jaeger-stack
type: application
home: https://github.com/obervinov/helm-charts/blob/main/jaeger-stack

keywords:
  - metrics
  - jaeger
  - otlp
  - monitoring

sources:
  - https://www.jaegertracing.io/docs/1.32/deployment/

deprecated: false

icon: https://helm.sh/img/helm.svg

maintainers:
  - name: obervinov
    email: o.bervinov@mail.ru
    url: https://github.com/obervinov

appVersion: "1.32.0"

dependencies:
  - name: elasticsearch
    version: ^7.11.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
