---
apiVersion: v2
name: terraform-operator-crds
version: 1.1.1
description: "This chart generating CRDs for Terraform Cloud Operator: Workspaces and AgentPools"
type: application
home: https://github.com/obervinov/helm-charts/blob/main/src/terraform-operator-crds
sources:
  - https://github.com/obervinov/helm-charts/blob/main/src/terraform-operator-crds

deprecated: false

icon: https://helm.sh/img/helm.svg

maintainers:
  - name: obervinov
    email: bervinov.ob@gmail.com
    url: https://github.com/obervinov

appVersion: "1.0.0"
