{{- if .Values.podMonitors }}
{{-   range .Values.podMonitors }}
{{-     $name := .name -}}
{{-     $fullName := include "chart.fullName" (list $ . $name) }}
---
apiVersion: {{ default "monitoring.coreos.com" $.Values.global.apiName }}/{{ default "v1" $.Values.global.apiVersion }}
kind: PodMonitor
metadata:
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
    jobLabel: {{ .jobLabel | quote }}
  name: {{ $fullName }}-podmonitor
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if .namespaceSelector}}
  namespaceSelector:
    {{- if .namespaceSelector.matchNames }}
    matchNames:
      {{- range .namespaceSelector.matchNames }}
      - {{ . }}
      {{- end }}
    {{- else }}
    any: true
    {{- end }}
  {{- end }}
  {{- if .labelSelectors }}
  selector:
    matchLabels:
      {{- range $k, $v := .labelSelectors }}
      {{ $k }}: {{ $v | quote }}
      {{- end }}
  {{- end }}
  podMetricsEndpoints: {{ toYaml .podMetricsEndpoints | nindent 2 }}
...
{{-   end }}
{{- end }}
