{{- if .Values.applications }}
{{-   range .Values.applications }}
{{-     if .configMap }}
{{-       $name := .name }}
{{-       $fullName := include "universal-template.fullName" (list $ . $name) }}
{{-       $namespace := $.Release.Namespace }}
{{-       $files     := .configMap.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
  name: {{ $fullName }}
  namespace: {{ $namespace }}
data:
{{-       range $files }}
{{-         if .data }}
{{-             printf "%s: |-" .name | nindent 2 }} {{- printf "%s" .data | nindent 4 -}}
{{-         end }}
{{-       end }}
...
{{-     end }}
{{-   end }}
{{- end }}
