
{{- if .Values.cronjobs }}
{{-   range .Values.cronjobs }}
{{-     $name := .name }}
{{-     $fullName := include "universal-template.fullName.cronjobs" (list $ . $name) }}

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $fullName }}-cronjob
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
spec:
  schedule: {{ .schedule | quote }}
  failedJobsHistoryLimit: {{ default 1 .failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ default 0 .successfulJobsHistoryLimit }}
  concurrencyPolicy: {{ default "Forbid" .concurrencyPolicy }} 
  jobTemplate:
    spec:
      parallelism: {{ default 1 .parallelism }}
      completions: {{ default 1 .completions }}
      backoffLimit: {{ default 3 .backoffLimit }}
      activeDeadlineSeconds: {{ default 600 .activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ default 300 .ttlSecondsAfterFinished }}
      template:
        spec:
          {{- if .initContainers }}
          initContainers:
          {{-   range .initContainers }}
          {{-     include "universal-template.containers.init.template" . | nindent 10 }}
          {{-   end }}
          {{- end }}
          {{- if .affinity }}
          affinity:
          {{-   toYaml .affinity | nindent 10 }}
          {{- end }}
          {{- if .nodeSelector }}
          nodeSelector:
          {{-   toYaml .nodeSelector | nindent 10 }}
          {{- end }}
          {{- if .tolerations }}
          tolerations:
          {{-   toYaml .tolerations | nindent 10 }}
          {{- end }}
          containers:
          - name: {{ $fullName }}-cronjob
            image: {{ .image.repository }}:{{ default $.Values.version .image.version }}
            imagePullPolicy: {{ .image.imagePullPolicy }}
            {{- if .resources }}
            resources: {{- toYaml .resources | nindent 14 }}
            {{- else }}
            resources: {{- include "universal-template.resources.default" . | nindent 14 }}
            {{- end }}
            {{- if .command }}
            command:
            {{-   range .command }}
            - {{ . | quote }}
            {{-   end }}
            {{- end }}
            {{- if or (.envs) (.envsSecret) }}
            env:
            {{- end }}
            {{- if .envs }}
            {{-   range $name, $value := .envs }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
            {{-   end }}
            {{- end }}
            {{- if and (.envsSecret) (.secret) }}
            {{-   range .envsSecret }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-cronjob-secret
                  key: {{ .keySecret }}
            {{-   end }}
            {{- end }}
          {{- if .configmap }}
            volumeMounts:
            - name: volume-configs
              mountPath: {{ .configmap.mountPath | lower }}
              readOnly: true
          volumes:
          - name: volume-configs
            configMap:
              name: {{ $fullName }}-cronjob-cm
              items:
              {{-   range .configmap.files }}
              - key: {{ .name | lower }}
                path: {{ .name | lower }}
              {{-   end }}
          {{- end }}
          {{- if .image.pullsecrets }}
          imagePullSecrets:
          - name: {{ .image.pullsecrets }}
          {{- end }}
          restartPolicy: {{ default "Never" .restartPolicy }}
          {{- if .volume }}
...
{{-   end -}}
{{- end -}}
