{{- if .Values.applications -}}
{{-   range .Values.applications -}}
{{-     if and (.ingress) (.service) -}}
{{-       $name             := .name }}
{{-       $fullName         := include "universal-template.fullName" (list $ . $name) }}
{{-       $namespace        := $.Release.Namespace }}
{{-       $apiVersion       := .ingress.apiVersion }}
{{-       $kind             := .ingress.Kind }}
{{-       $extraAnnotations := .ingress.extraAnnotations }}
{{-       $useTLS           := .ingress.useTLS }}
{{-       $fqdn             := .ingress.fqdn }}
{{-       $paths            := .ingress.paths }}
{{-       $ingressClassName := .ingress.ingressClassName }}
apiVersion: {{ default "networking.k8s.io/v1" $apiVersion }}
kind: {{ default "Ingress" $kind }}
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
  {{- if $extraAnnotations }}
  annotations:
  {{-   toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $useTLS }}
  tls:
    - hosts:
        - {{ $fqdn }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
  - host: {{ $fqdn }}
    http:
      paths:
      {{- range $paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $fullName }}
            port:
              {{- if .servicePortName }}
              name: {{ .servicePortName }}
              {{- else }}
              number: {{ .servicePort }}
              {{- end }}
      {{- end }}
  ingressClassName: {{ default "nginx" $ingressClassName }}
...
{{-     end -}}
{{-   end }}
{{- end }}
