{{- if .Values.applications                                                               }}
{{-   range .Values.applications                                                          }}
{{-     if .app                                                                           }}
{{-       if eq .app.type "job"                                                           }}
{{-         $configMap          := .configMap                                             }}
{{-         $secret             := .secret                                                }}
{{-         $name               := .name                                                  }}
{{-         $namespace          := $.Release.Namespace                                    }}
{{-         $fullName           := include "universal-template.fullName" (list $ . $name) }}
{{-         $app                := .app                                                   }}
{{-         $extraLabels        := $app.extraLabels                                       }}
{{-         $podAnnotations     := $app.podAnnotations                                    }}
{{-         $image              := $app.image                                             }}
{{-         $initContainers     := $app.initContainers                                    }}
{{-         $containers         := $app.containers                                        }}
{{-         $envs               := $app.envs                                              }}
{{-         $resources          := $app.resources                                         }}
{{-         $persistentVolume   := $app.persistentVolume                                  }}
{{-         $emptyDirVolume     := $app.emptyDirVolume                                    }}
{{-         $tolerations        := $app.tolerations                                       }}
{{-         $affinity           := $app.affinity                                          }}
{{          $nodeSelector       := $app.nodeSelector                                      }}
{{-         $probes             := $app.probes                                            }}
{{-         $commands           := $app.commands                                          }}
{{-         $args               := $app.args                                              }}
{{-         $job                := $app.job                                               }}
{{          $externalSecrets    := $app.externalSecrets                                   }}
{{          $externalConfigMaps := $app.externalConfigMaps                                }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $fullName }}-{{ now | unixEpoch }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
    {{- if $extraLabels }}
    {{-   toYaml $extraLabels | nindent 4 }}
    {{- end }}
spec:
  parallelism: {{ default 1 $job.parallelism }}
  completions: {{ default 1 $job.completions }}
  backoffLimit: {{ default 3 $job.backoffLimit }}
  activeDeadlineSeconds: {{ default 600 $job.activeDeadlineSeconds }}
  ttlSecondsAfterFinished: {{ default 300 $job.ttlSecondsAfterFinished }}
  template:
    spec:
      {{- if $affinity }}
      affinity: {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if $nodeSelector }}
      nodeSelector: {{- toYaml $nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $tolerations }}
      tolerations: {{- toYaml $tolerations | nindent 8 }}
      {{- end }}
      {{- if $initContainers }}
      initContainers:
      {{-   range $initContainers }}
      {{-     $initContainerData := dict "app" . "name" .name "configMap" $configMap "secret" $secret "externalSecrets" $externalSecrets "externalConfigMaps" $externalConfigMaps "persistentVolume" $persistentVolume "emptyDirVolume" $emptyDirVolume }}
      {{- include "universal-template.container.template" $initContainerData | nindent 8 }}
      {{-   end }}
      {{- end }}
      containers:
      {{- range $containers }}
      {{- $containerData := dict "app" . "name" .name "configMap" $configMap "secret" $secret "externalSecrets" $externalSecrets "externalConfigMaps" $externalConfigMaps "persistentVolume" $persistentVolume "emptyDirVolume" $emptyDirVolume }}
      {{- include "universal-template.container.template" $containerData | nindent 8 }}
      {{- end }}
      {{- if or $configMap $secret $persistentVolume $emptyDirVolume $externalSecrets $externalConfigMaps }}
      {{-   $volumesData := dict "targetType" "job" "fullName" $fullName "configMap" $configMap "secret" $secret "externalSecrets" $externalSecrets "externalConfigMaps" $externalConfigMaps "persistentVolume" $persistentVolume "emptyDirVolume" $emptyDirVolume }}
      volumes: {{- include "universal-template.volumes.template" $volumesData | nindent 8 }}
      {{- end }}
      {{- if $image.pullSecrets }}
      imagePullSecrets:
      {{-   range $image.pullSecrets }}
        - name: {{ . }}
      {{-   end }}
      {{- end }}
      restartPolicy: {{ $job.restartPolicy | default "Never" }}
  backoffLimit: {{ $job.backoffLimit | default 1 }}
...
{{-       end }}
{{-     end }}
{{-   end }}
{{- end }}
