{{- if .Values.applications }}
{{-   range .Values.applications }}
{{-     if .app.persistentVolume }}
{{-       if or (eq .app.type "deployment") (eq .app.type "cronjob") (eq .app.type "job") }}
{{-         $name := .name }}
{{-         $fullName := include "universal-template.fullName" (list $ . $name) }}
{{-         $namespace := $.Release.Namespace }}
{{-         $persistentVolume := .app.persistentVolume }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName )  | nindent 4 }}
  name: {{ $fullName }}
  namespace: {{ $namespace }}
spec:
  accessModes:
  {{-         if $persistentVolume.accessModes }}
  {{-           range $persistentVolume.accessModes }}
    - {{ . }}
  {{-           end }}
  {{-         else }}
    - ReadWriteOnce
  {{-         end }}
  resources:
    requests:
      storage: {{ $persistentVolume.size }}
  {{-         if $persistentVolume.storageClassName }}
  storageClassName: {{ $persistentVolume.storageClassName }}
  {{-         end }}
...
{{-       end }}
{{-     end }}
{{-   end }}
{{- end }}
