{{- if .Values.rbac }}
{{-   range .Values.rbac }}
{{-     $name := .name }}
{{-     $fullName := include "universal-template.fullName.rbac" (list $ . $name) }}

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
rules:
{{- range .rules }}
  - apiGroups:
    {{-   range .apiGroups }}
      - {{ . | quote }}
    {{-   end }}   
    resources:
    {{-   range .resources }}
      - {{ . | quote }}
    {{-   end }}   
    verbs:
    {{-   range .verbs }}
      - {{ . | quote }}
    {{-   end }}  
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}-sa
    namespace: "{{ $.Release.Namespace }}"
roleRef:
  kind: Role
  name: {{ $fullName }}-role
  apiGroup: rbac.authorization.k8s.io
...
{{-   end }}
{{- end }}