{{- if .Values.applications                                                                 }}
{{-   range .Values.applications                                                            }}
{{-     if .rbac                                                                            }}
{{-       $name                   := .name                                                  }}
{{-       $fullName               := include "universal-template.fullName" (list $ . $name) }}
{{-       $namespace              := $.Release.Namespace                                    }}
{{-       $rbac                   := .rbac                                                  }}
{{-       $rules                  := $rbac.rules                                            }}
{{-       $createServiceAccount   := $rbac.create                                           }}
{{-       $createLegacyToken      := $rbac.legacyToken                                      }}
{{-       $existingServiceAccount := $rbac.useExistingServiceAccount                        }}
{{-       $extraLabels            := $rbac.extraLabels                                      }}
{{-       $extraAnnotations       := $rbac.extraAnnotations                                 }}

{{-       if $createServiceAccount }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
    {{- if $extraLabels }}
    {{- toYaml $extraLabels | nindent 4 }}
    {{- end }}
  {{- if $extraAnnotations }}
  annotations: {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
...

{{-         if $createLegacyToken }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullName }}-token
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
  {{- if $extraLabels }}
    {{- toYaml $extraLabels | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/service-account.name: {{ $fullName }}
    {{- if $extraAnnotations }}
    {{- toYaml $extraAnnotations | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
...
{{-         end }}
{{-         if $rules }} 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
    {{- if $extraLabels }}
    {{- toYaml $extraLabels | nindent 4 }}
    {{- end }}
  {{- if $extraAnnotations }}
  annotations: {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
rules:
{{-           range $rules }}
  - apiGroups:
    {{-         range .apiGroups }}
      - {{ . | quote }}
    {{-         end }}   
    resources:
    {{-         range .resources }}
      - {{ . | quote }}
    {{-         end }}   
    verbs:
    {{-         range .verbs }}
      - {{ . | quote }}
    {{-         end }}
{{-           end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
    {{- if $extraLabels }}
    {{- toYaml $extraLabels | nindent 4 }}
    {{- end }}
  {{- if $extraAnnotations }}
  annotations: {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: {{ $fullName }}
  apiGroup: rbac.authorization.k8s.io
...
{{-         end }}
{{-       end }}
{{-     end }}
{{-   end }}
{{- end }}