{{- if .Values.applications }}
{{-   range .Values.applications }}
{{-     if .rbac }}
{{-       $name      := .name }}
{{-       $fullName  := include "universal-template.fullName" (list $ . $name) }}
{{-       $namespace := $.Release.Namespace }}
{{-       $rbac     := .rbac }} 
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
rules:
{{- range $rbac }}
  - apiGroups:
    {{-   range .apiGroups }}
      - {{ . | quote }}
    {{-   end }}   
    resources:
    {{-   range .resources }}
      - {{ . | quote }}
    {{-   end }}   
    verbs:
    {{-   range .verbs }}
      - {{ . | quote }}
    {{-   end }}  
{{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: {{ $fullName }}
  apiGroup: rbac.authorization.k8s.io
...
{{-     end }}
{{-   end }}
{{- end }}