{{- if .Values.applications }}
{{-   range .Values.applications }}
{{-     if .secret }}
{{-       $name := .name }}
{{-       $fullName := include "universal-template.fullName" (list $ . $name) }}
{{-       $namespace := $.Release.Namespace }}
{{-       $data := .secret.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName )  | nindent 4 }}
type: Opaque
data:
{{- with index . 1 }}
{{-   range $key, $value := fromYaml $data }}
  {{ $key }}: {{ $value | b64enc }}
{{-   end }}
{{- end }}
...
{{-     end }}
{{-   end }}
{{- end }}
