{{- if .Values.applications }}
{{-   range .Values.applications }}
{{-     if .secret }}
{{-       $name := .name }}
{{-       $fullName := include "universal-template.fullName" (list $ . $name) }}
{{-       $namespace := $.Release.Namespace }}
{{-       $data := .secret.data }}
{{-       $extraLabels := .secret.extraLabels }}
{{-       $extraAnnotations := .secret.extraAnnotations }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName )  | nindent 4 }}
    {{- if $extraLabels }}
    {{- toYaml $extraLabels | nindent 4 }}
    {{- end }}
  {{- if $extraAnnotations }}
  annotations: {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{-       range $key, $value := fromYaml $data }}
  {{ $key }}: {{ toString $value | b64enc }}
{{-       end }}
...
{{-     end }}
{{-   end }}
{{- end }}
