{{- if .Values.applications }}
{{-   range .Values.applications }}
{{-     if .service -}}
{{-       $name                  := .name }}
{{-       $namespace             := $.Release.Namespace }}
{{-       $fullName              := include "universal-template.fullName" (list $ . $name) }}
{{-       $extraLabels           := .service.extraLabels }}
{{-       $extraAnnotations      := .service.extraAnnotations }}
{{-       $type                  := .service.type }}
{{-       $ports                 := .service.ports }}
{{-       $externalIPs           := .service.externalIPs }}
{{-       $externalTrafficPolicy := .service.externalTrafficPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
  labels:
    {{- include "universal-template.labels" $ | nindent 4 }}
    {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
  {{- if $extraLabels }}
  {{-   toYaml $extraLabels | nindent 4 }}
  {{- end }}
  {{- if $extraAnnotations }}
  annotations:
    {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
spec:
{{- if eq $type "ClusterIP" }}
  type: ClusterIP
{{- else if eq $type "NodePort" }}
  type: NodePort
{{- else if eq $type "LoadBalancer" }}
  type: LoadBalancer
{{- end }}
  ports:
  {{- range $ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  {{- if $externalIPs }}
  externalIPs:
  {{- range $externalIPs }}
  - {{ . }}
  {{- end }}
  {{- end }}
  {{- if $externalTrafficPolicy }}
  externalTrafficPolicy: {{ $externalTrafficPolicy }}
  {{- end }}
  selector: {{- include "universal-template.selectorLabels" (list $fullName) | nindent 4 }}
...
{{-     end }}
{{-   end }}
{{- end }}