global:
  apiName: monitoring.coreos.com
  apiVersion: v1

serviceMonitors:
  - name: istiod
    type: ServiceMonitor
    endpoints:
      - port: http-metrics
        # bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
        # honorLabels: true
        path: /stats/prometheus
        interval: 30s
        scheme: http
    jobLabel: k8s-app
    namespaceSelectors:
      - istio-system
    labelSelectors:
      app: istiod

podMonitors:
  - name: istio-proxy
    type: podMonitor
    ports:
      - http-envoy-prom
    jobLabel: k8s-app
    labelSelectors:
      istio-proxy: true
