---
name: Checks and Build Helm-Charts Bundle

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  pr:
    uses: obervinov/_templates/.github/workflows/pr.yaml@v2.0.2

  download-crds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "1.8.3"

      - name: Install dependencies
        run: cd scripts && poetry install
      
      - name: Download CRDs
        run: cd scripts && poetry run python download-crds.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Include CRDs for Helm-Charts Bundle from ${{ github.ref }}"
          branch: ${{ github.ref }}

  helm-repository-build:
    uses: obervinov/_templates/.github/workflows/helm-charts.yaml@v2.0.2
    needs: [download-crds]
