---
name: Checks and Build Helm-Charts Bundle

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'

jobs:
  helm-repository-build:
    uses: obervinov/_templates/.github/workflows/helm.yaml@release/v1.2.0

  readme:
    uses: obervinov/_templates/.github/workflows/readme.yaml@release/v1.2.0
  
  pr:
    uses: obervinov/_templates/.github/workflows/pr.yaml@release/v1.2.0
  
  milestone:
    uses: obervinov/_templates/.github/workflows/milestone.yaml@release/v1.2.0

  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@release/v1.2.0
