---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v2.1.0
