---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.2.0
  
  readme:
    uses: obervinov/_templates/.github/workflows/readme.yaml@v1.2.0

  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v1.2.0
    needs: [changelog, readme]
