---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v1.2.0

  milestone:
    uses: obervinov/_templates/.github/workflows/milestone.yaml@v1.2.0
    needs: [create-release]
