---
name: Create GitHub Release

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  helm-repository-build:
    uses: obervinov/_templates/.github/workflows/helm.yaml@v1.0.12

  changelog:
    uses: obervinov/_templates/.github/workflows/changelog.yaml@v1.1.0
  
  # readme:
  #   uses: obervinov/_templates/.github/workflows/readme.yaml@v1.1.0

  create-release:
    uses: obervinov/_templates/.github/workflows/release.yaml@v1.1.0
    needs: [helm-repository-build, changelog]
