---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wireguard-operator.fullname" . }}-manager-config
  labels:
    control-plane: controller-manager
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: a6d3bffc.wireguard-operator.io
...