---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    {{- include "wireguard-operator.labels" . | nindent 4 }}
  name: {{ include "wireguard-operator.fullname" . }}-controller-manager-metrics-service
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    {{- include "wireguard-operator.labels" . | nindent 8 }}
...